flowchart TB
  __start__(__start__)
  translate_email_language(translate_email_language)
  extract_order_id(extract_order_id)
  get_order_details(get_order_details)
  auto_reject(auto_reject)
  categorize_email(categorize_email)
  analyze_email_sentiment(analyze_email_sentiment)
  get_answer_to_query(get_answer_to_query)
  human_review(human_review)
  reply_to_email(reply_to_email)
  step_end(step_end)
  __end__(__end__)
  __start__ --> translate_email_language
  analyze_email_sentiment --> get_answer_to_query
  auto_reject --> step_end
  categorize_email --> analyze_email_sentiment
  extract_order_id --> |order_id_missing|auto_reject
  extract_order_id --> |order_id_available|get_order_details
  get_answer_to_query --> |very_negative_sentiment|human_review
  get_answer_to_query --> |agent_can_proceed_sentiment|reply_to_email
  get_order_details --> categorize_email
  human_review --> reply_to_email
  reply_to_email --> step_end
  translate_email_language --> extract_order_id
  step_end --> __end__
